### ISSUE TITLE
Nextbit Robin (Snapdragon 808?) support

### ISSUE THREAD

**Issue by alexbirkett** [quiet/org.quietmodem.Quiet#1]
I built an example app that runs on the Samsung Galaxy S5 but not the NextBit Robin. I assume this is because the Snapdragon 808 is not supported.

**Comment by alexbirkett** [comment]
I can reproduce the same problem on the LG K8 (also Snapdragon 808 based)

The app I used to test is [here](https://github.com/alexbirkett/QuietShare)

This is the exception 
```604-11604/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: no.birkett.quietshare, PID: 11604
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{no.birkett.quietshare/no.birkett.quietshare.MainActivity}: java.lang.RuntimeException: org.quietmodem.Quiet.ModemException: failed to initialize opensl recorder, opensl error code=0009
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
                                                    Caused by: java.lang.RuntimeException: org.quietmodem.Quiet.ModemException: failed to initialize opensl recorder, opensl error code=0009
                                                       at no.birkett.quietshare.MainActivity.setup(MainActivity.java:56)
                                                       at no.birkett.quietshare.MainActivity.onCreate(MainActivity.java:35)
                                                       at android.app.Activity.performCreate(Activity.java:6272)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) 
                                                    Caused by: org.quietmodem.Quiet.ModemException: failed to initialize opensl recorder, opensl error code=0009
                                                       at org.quietmodem.Quiet.BaseFrameReceiver.nativeOpen(Native Method)
                                                       at org.quietmodem.Quiet.BaseFrameReceiver.<init>(BaseFrameReceiver.java:23)
                                                       at org.quietmodem.Quiet.FrameReceiver.<init>(FrameReceiver.java:15)
                                                       at no.birkett.quietshare.MainActivity.setup(MainActivity.java:53)
                                                       at no.birkett.quietshare.MainActivity.onCreate(MainActivity.java:35) 
                                                       at android.app.Activity.performCreate(Activity.java:6272) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5551) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620) ```

**Comment by alexbirkett** [comment]
So this issue nothing to do with the processor. The problem is caused by missing permissions on Android 6.0

**Comment by brian-armstrong** [comment]
I'm glad to hear you figured it out. Let me know how the app turns out 👍
