### ISSUE TITLE
Error after adding Quiet library

### ISSUE THREAD

**Issue by hosseinpro** [quiet/org.quietmodem.Quiet#12]
Hi
I built Quiet successfully and added "quiet-debug.aar" to my app project. In addition, I added "    compile project(':quiet-debug')" to "build.gradle".
When I compile my project its ok, but when I run it I get this error:

AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: ..., PID: 14939
                                                   java.lang.NoSuchFieldError: No field abc_seekbar_tick_mark_material of type I in class Landroid/support/v7/appcompat/R$drawable; or its superclasses (declaration of 'android.support.v7.appcompat.R$drawable' appears in /data/app/net.ezlogin.ezloginapp-1/split_lib_dependencies_apk.apk:classes6.dex)
                                                       at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:120)
                                                       at android.support.v7.widget.AppCompatDrawableManager.get(AppCompatDrawableManager.java:84)
                                                       at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
                                                       at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:129)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:152)
                                                       at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:29)
                                                       at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:53)
                                                       at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:31)
                                                       at android.support.v7.app.AppCompatDelegateImplN.<init>(AppCompatDelegateImplN.java:31)
                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:200)
                                                       at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:184)
                                                       at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:518)
                                                       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
                                                       at net.ezlogin.ezloginapp.MainActivity.onCreate(MainActivity.java:16)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by hosseinpro** [comment]
Finally, I found the problem. I created an empty activity and removed "Backward Compatibility (AppCompat)". So, my problem have been solved.
